#!/usr/bin/env bash
# displays I am invincible!!! when receiving a SIGTERM signal
x=0
while [ $x -le 5 ]
x=$((x++))
do
    echo "To infinity and beyond"
    sleep 2
trap "echo I am invincible!!!" 15
done
